### ISSUE TITLE
No 'rescale.json' available

### ISSUE THREAD

**Issue by dragonlong** [facebookresearch/d3d-hoi#3]
Hi, 

Thanks for the efforts! I am trying to follow the post-processing steps over Sapien data, since no post-processed CAD models are provided. However, it seems besides the IDs, we still need to at least have the rough scales to scale the processed CAD models. Could you also provide that together with other necessary middle files to get the final meshes? Thanks!

Best,
Xiaolong

**Comment by samxuxiang** [comment]
Hi Xiaolong, the processed meshes are all in unit cube (-1 ~ 1). You can follow the instructions in preprocess folder. The actual object dimensons and rescaling values to transform the object to world coordinate are provided in `3d_info.txt` of the video dataset (see line 10 obj_size). I have also uploaded the motion.json parameters if this helps.
