### ISSUE TITLE
About getting 'rescale.json'

### ISSUE THREAD

**Issue by liangpan99** [facebookresearch/d3d-hoi#5]
Hi,

I've seen your answer in #3, but i'm still confused how to get the `rescale.json` which is used in `re-meshing.py`.

According to the codes on lines 37-40 in `re-meshing.py`, what we want from `rescale.json`  is **scales** and **translation** parameters , and i think that we should use these parameters to rescale the 3d object to unit cube and move the origin of the object to the the origin of world coordinate (0, 0, 0). 

So,  can i use the  object's bounding box information which provided by the partnet-mobility-v0 dataset as the scales and translation parameters?

Best,
Liang

**Comment by liangpan99** [comment]
sorry, wrong happend in `python conver_off.py` i forgot to install meshlab......

**Comment by Steve-Tod** [comment]
Hi, did you get `rescale.json` after successfully running `python conver_off.py`? I still can't find it...
